apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority: ca.crt
    server: https://127.0.0.1:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    namespace: homework
    user: cd
  name: cd-context
current-context: cd-context
users:
- name: cd
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkVhWVZhX0VsSkNhZXRiVmN1ZTJwTV8zdjVDOUZDTk5SS1J0VjlqZjVPaFkifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzU3NzYyMjQ0LCJpYXQiOjE3NTc3NTIyNDQsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiYTI3ZmEyNGEtNjFhOC00MGE2LTMxODktY2I3N2I1NzY1MnZhIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJob21ld29yayIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJjZCIsInVpZCI6ImMwOTZmYjI5LTNlMjgtNGY2YS1mNDYtZjRkYTBiNnAzMmQxIn19LCJuYmYiOjE3NTcyNDc5NzQsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpob21ld29yazpjZCJ9.oCwWFBRtNihgmkhX5n49Zn4x8F_8swaGS7XqxmIJrNkLqNQn2pCl9flOSBy3_7XagzYZWmzeJzFLxG35p4MSFIeX_8qT2GvfpL7dMm83rK0xxDjzbN8-rwTwMtBNp-K8KzJJ0rl6Q3XFJYnrG98m_UhKUWOmqciFgGT1VsuZ_O3B9tCHi41JDdZBPoXsaEN6T3v5Iw3NF1rJ6e_9nvnU_yDRcQfiXJ5icty5d4kR_VEMKeXoSuAXkDCSbDhRH5rLZyhWJ_DpWyaDrifpSkZFyFUGJwNNifmO5Jl8MK9aAYNz5C1kdYIAWC5Ytcny1h0JJ3K81LeAmutrUa2aejHXcQ
